### PR TITLE
Add translation possibility for missing buttons

### PR DESCRIPTION
**Pull request by rabelux**
Hi @xupefei,
as users keep asking for translations I thought I'd give it a go.
I know python and matlab but unfortunately no c# so I need your input whether this goes in the right direction.
My changes weren't tested and I pushed these changes online.
Take your time if you're busy atm, I'm in no rush for having these translations.

### CODE REVIEW

**Comment by xupefei** [comment]
Thanks @rabelux! Is this PR ready for review?

**Comment by rabelux** [comment]
Sure, if you think what I did could work? 😄

**Comment by dracp** [comment]
[](https://github.com/rabelux)@rabelux
[Add translation possibility for missing buttons pt2](https://github.com/QL-Win/QuickLook/pull/1116/commits/df2565c7dba6663387f55b5ed446826e309e7819)

Translation Spanish ES (Translations.config)
<es>
    <UI_FontFamily>Segoe UI</UI_FontFamily>
    <APP_START>QuickLook está funcionando en segundo plano.</APP_START>
    <APP_SECOND>QuickLook ya está funcionando en segundo plano</APP_SECOND>
    <APP_SECOND_TEXT>QuickLook permite la previsualización rápida de ciertos tipos de archivos pulsando la barra espaciadora mientras este está resaltado.</APP_SECOND_TEXT>
    <APP_PATH_NOT_WRITABLE>No se puede escribir en la ruta "{0}". Por favor, compruebe si tiene suficientes permisos.</APP_PATH_NOT_WRITABLE>
    **<MW_StayTop>Siempre Encima</MW_StayTop>**
    **<MW_PreventClosing>Evitar Cierre</MW_PreventClosing>**
    <MW_BrowseFolder>Explorar {0}</MW_BrowseFolder>
    <MW_Open>Abrir {0}</MW_Open>
    <MW_OpenWith>Abrir con {0}</MW_OpenWith>
    **<MW_OpenWithMenu>Abrir Con Menu</MW_OpenWithMenu>**
    <MW_Run>Iniciar {0}</MW_Run>
    **<MW_Share>Compartir</MW_Share>**
    <Icon_RunAtStartup>Iniciar con el &amp;sistema</Icon_RunAtStartup>
    <Icon_ToolTip>QuickLook v{0}</Icon_ToolTip>
    <Icon_CheckUpdate>Buscar &amp;Actualizaciones...</Icon_CheckUpdate>
    <Icon_GetPlugin>Buscar nuevos &amp;Plugins...</Icon_GetPlugin>
    <Icon_Quit>&amp;Salir</Icon_Quit>
    <Update_NoUpdate>Está usando la última versión.</Update_NoUpdate>
    <Update_Found>QuickLook {0} está disponible. Haga clic aquí para abrir la página de descarga.</Update_Found>
    <Update_Error>Ocurrió un error al buscar actualizaciones: {0}</Update_Error>
    <InfoPanel_LastModified>Última modificación el {0}</InfoPanel_LastModified>
    <InfoPanel_DriveSize>Capacidad {0}, {1} disponible</InfoPanel_DriveSize>
    <InfoPanel_Folder>{0} carpeta</InfoPanel_Folder>
    <InfoPanel_Folders>{0} carpetas</InfoPanel_Folders>
    <InfoPanel_File>{0} archivo</InfoPanel_File>
    <InfoPanel_Files>{0} archivos</InfoPanel_Files>
    <InfoPanel_FolderAndFile>({0} y {1})</InfoPanel_FolderAndFile>
  </es>

**Comment by rabelux** [comment]
@xupefei does my approach look good to you? Can this be merged?

**Comment by xupefei** [comment]
Thanks for the PR!
We don't need to load translations on every preview, but once during window initialization, i.e., somewhere here: https://github.com/QL-Win/QuickLook/blob/master/QuickLook/ViewerWindow.xaml.cs#L99. Just make sure they come after `InitializeComponent()`.

**Review by Shawnblake — APPROVED** [review]

**Comment by xupefei** [comment]
Hey @rabelux, any updates on this PR? After you change I want to contribute Chinese and Japanese translations to this PR 😀

**Comment by rabelux** [comment]
Hi @xupefei, I'm really short on time at the moment and as I'm not really having a clue what I'm doing here, could you finish what I started? I think I allowed edits by maintainers for this PR.

**Pull request merged**
