### PR TITLE
Github action workflow to run a build for the latest version

### PR DESCRIPTION
**Pull request by mooflu**
and upload the artifacts to a "latest" pre-release.

### CODE REVIEW

**Comment by emako** [comment]
Sorry for auto release is not currently considered, which may bring risks.

However, we may consider joining it in the future.

**Comment by mooflu** [comment]
Ok, it was meant as a replacement for appveyor.yml to do nightly builds. Not sure why you think this is riskier.

**Comment by emako** [comment]
OK, I mistakenly thought that the latest release would be modified instead of pre-release.

https://github.com/pyTooling/Actions/tree/main/releaser

**Comment by emako** [comment]
I am going to test CI result and it runs as expected.

https://github.com/emako/QLTest/actions/runs/12204827007

**Comment by emako** [comment]
Thanks a lot！

**Comment by mooflu** [comment]
If you add a special tag it puts the files in the release area. This MR uses "latest"

On my fork I use "experimental": 
https://github.com/mooflu/QuickLook/blob/experimental/.github/workflows/msbuild.yml#L72

which then goes to https://github.com/mooflu/QuickLook/releases/tag/experimental

**Pull request merged**
