### PR TITLE
Simple RTF support via RichTextBox.

### PR DESCRIPTION
**Pull request by mooflu**
I added it to the TextViewer plugin since it's only a few extra lines. Let me know if you prefer it as its own plugin.

### CODE REVIEW

**Comment by xupefei** [comment]
Your solution is fine. Thanks!

**Comment by technobulb** [comment]
Wow! Amazing job. Thanks, it makes such a difference for me!

**Comment by zhixuanzhao** [comment]
hi,  I can open rtf file , but it display empty.  I donot know why .  thank you ~.

**Comment by zhixuanzhao** [comment]
> 
i use quick look v3.7.0

**Comment by technobulb** [comment]
> hi, I can open rtf file , but it display empty. I donot know why . thank you ~.

Is it only one file? Or all .rtf files? Maybe try uploading the file you are having issues with, and I can see if it works for me.

**Comment by zhixuanzhao** [comment]
> > hi, I can open rtf file , but it display empty. I donot know why . thank you ~.
> 
> Is it only one file? Or all .rtf files? Maybe try uploading the file you are having issues with, and I can see if it works for me.

Thank you very much. I have find the problem， if I setup  officeviewer v4 Plugin, then  can open word  but the rtf file can not open  (only when  do not setup officeviewer v4 Plugin i can open .rtf files, but word can not open.) .  I want to know how to open word and rtf file at the same time.

**Pull request merged**
