### PR TITLE
Add support for .aif audio files

### PR DESCRIPTION
**Pull request by Jethro-Alter**

### CODE REVIEW

**Comment by xupefei** [comment]
Thanks! Just want to be sure, have you tested the change with an AIF file?

**Comment by Jethro-Alter** [comment]
Tested with: https://example-files.online-convert.com/audio/aif/example.aif

**Comment by Jethro-Alter** [comment]
Tested .m4r with: https://example-files.online-convert.com/audio/m4r/example.m4r

**Comment by xupefei** [comment]
Got it. Are you planning to add more extension or I shall merge this PR now?

**Comment by Jethro-Alter** [comment]
Please complete this PR.
More to be included in the near future.

**Comment by xupefei** [comment]
Done. Thanks!

**Pull request merged**
