### PR TITLE
Update Translations.config

### PR DESCRIPTION
**Pull request by Piteriuz**
Adding 1 line in polish translation

### CODE REVIEW

**Comment by xupefei** [comment]
Thanks! Could you also add hotkeys to the other two menu items?
```
    <Icon_CheckUpdate>Sprawdź aktualizacje...</Icon_CheckUpdate>
    <Icon_Quit>Zakończ</Icon_Quit>
```
The character after `&amp;` becomes the hotkey.

**Comment by Piteriuz** [comment]
> Thanks! Could you also add hotkeys to the other two menu items?
> 
> ```
>     <Icon_CheckUpdate>Sprawdź aktualizacje...</Icon_CheckUpdate>
>     <Icon_Quit>Zakończ</Icon_Quit>
> ```
> 
> The character after `&amp;` becomes the hotkey.

done

**Comment by xupefei** [comment]
Now there are two menus using the same hotkey, which is not allowed.
Maybe the second one can be `Znajdź nowe &amp;pluginy`?

**Comment by xupefei** [comment]
Now it's all set. Thank you!

**Pull request merged**
