### PR TITLE
Info-Overlay for Images/Videos

### PR DESCRIPTION
**Pull request by flipswitchingmonkey**
Added an info overlay (and icon in toolbar) to show file info based on exiv2 and ffprobe data.
Also fixed two typos...

### CODE REVIEW

**Comment by xupefei** [comment]
Thanks, really excellent work! I will look into it in a few days.

**Comment by xupefei** [comment]
I have looked into the code and found that it is not compatible with the latest base. Your PR is based on the `master` branch, while at that time I am working on the `vlc` branch.

I have added an small icon for the image viewer before you, but clearly your solution is much more beautiful than mine. I will accept and rebase your changes soon.

**Comment by flipswitchingmonkey** [comment]
Ah, sorry, didn't know you were working on another branch. I tried to make as few changes to the original code as possible,

**Comment by flipswitchingmonkey** [comment]
Hi! Are you still working on replacing exiv2 or is this done as well?

**Comment by xupefei** [comment]
The exiv2 transition has just completed, and yet I haven't got time to work on this because a release is more urgent -- almost half year without an upgrade.

I will work on this PR soon.

**Comment by tt12htc** [comment]
nice tool

**Comment by flipswitchingmonkey** [comment]
Hi! Has it made it into the build yet?

**Comment by tt12htc** [comment]
> Hi! Has it made it into the build yet?

I've just used it. Very convinient!

**Comment by JuDelCo** [comment]
Waiting for this !

**Comment by samytichadou** [comment]
Hi what a a great addition to a great piece of soft ;) (thks btw !)
Is there any release with file info available yet ? cheers !

**Comment by JanRajnoha** [comment]
What's current status of PR?

**Comment by SplitGemini** [comment]
Hope it be implemented

**Comment by Cyberdroid1** [comment]
Any updates to this?

**Comment by Cyberdroid1** [comment]
Why is this closed?

**Comment by flipswitchingmonkey** [comment]
> Why is this closed?

Because it's been sitting here for two years and I did not want to have it in my list of open PRs forever ;)

**Comment by Cyberdroid1** [comment]
I think the best way would be to implement this feature ASAP 😃

**Pull request closed without merging**
